In [3]:
import pandas as pd

# Creazione della lista degli studenti con i voti
studenti = {
    'nome': ['Massa', 'Anntonella', 'Luigi', 'Eduardo', 'Matteo', 'Stefano', 'Lucia', 'Annaritantonia', 'Paolo', 'Francesca'],
    'voti':  [10, 8, 9, 7, 10, 6, 5, 4, 10, 8]
}


# Creazione del DataFrame(Foglio excel, Tabella, Entità)
df = pd.DataFrame(studenti)

print(df)

             nome  voti
0           Massa    10
1      Anntonella     8
2           Luigi     9
3         Eduardo     7
4          Matteo    10
5         Stefano     6
6           Lucia     5
7  Annaritantonia     4
8           Paolo    10
9       Francesca     8

In [5]:
df

             nome  voti
0           Massa    10
1      Anntonella     8
2           Luigi     9
3         Eduardo     7
4          Matteo    10
5         Stefano     6
6           Lucia     5
7  Annaritantonia     4
8           Paolo    10
9       Francesca     8

La funzione info() restituisce l'infromazione del DataFrame()

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    10 non-null     str
 1   voti    10 non-null     int64
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

le funzione di agreazione del DataFrame()
- count  => somma 
- mean   => media
- min    => minimo
- max    => massimo

In [14]:
print(df.describe())

            voti
count  10.000000
mean    7.700000
std     2.162817
min     4.000000
25%     6.250000
50%     8.000000
75%     9.750000
max    10.000000

# Filtrare dati
- Studenti promossi

In [8]:
promossi = df[df['voti'] >= 9]
promossi

     nome  voti
0   Massa    10
2   Luigi     9
4  Matteo    10
8   Paolo    10

<h3><i>Calcolare la media</i></h3>

In [11]:
media = df['voti'].mean()
print(media)

7.7

<h3>Salvataggio in un file csv</h3>

In [16]:
# creazionde del DataFrame(dipendenti) => dataset, entità, foglio excel con record
dipendenti = {
    "nome": ["Mario", "Rudy", "Marco", "Luca", "Giovanni", "Francesco", "Giulia", "Elena", "Federica", "Alessandro"],
    "cognome": ["Ricci", "Botosso", "Secci", "Bianchi", "Neri", "Rossi", "Verdi", "Gialli", "Blu", "Rosa"],
    "email": ["mario.ricci@example.info", None, "marco.secci@example.com", None, "giovanni.neri@example.com", "francesco.rossi@example.ue", "giulia.verdi@example.com", "elena.gialli@example.it", "federica.blu@example.com", "alessandro.rosa@example.info"],
    "eta": [30, 54, 54, 28, 35, 42, 28, 32, 29, 31],
    "citta": ["Milano", "Biella", "San Donà di Piave", "Roma", "Napoli", "Torino", "Firenze", "Bologna", "Genova", "Padova"],
    "stipendio": [2000, 3000, 1500, 2500, 3500, 4000, 2500, 3000, 3500, 4000],
    "ruolo": ["Sviluppatore", "Project Manager", "Analista", "Sviluppatore", "Team Leader", "Project Manager", "Sviluppatore", "Analista", "Team Leader", "Project Manager"],
    "data_assunzione": ["2015-01-15", "2010-06-30", "2018-09-01", "2016-03-20", "2012-11-05", "2008-04-10", "2017-07-25", "2014-02-18", "2013-12-12", "2009-08-01"]
}


df = pd.DataFrame(dipendenti)
df

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
1,Rudy,Botosso,NaN,54,Biella,3000,Project Manager,2010-06-30
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,1500,Analista,2018-09-01
3,Luca,Bianchi,NaN,28,Roma,2500,Sviluppatore,2016-03-20
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,3500,Team Leader,2012-11-05
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,4000,Project Manager,2008-04-10
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25
7,Elena,Gialli,elena.gialli@example.it,32,Bologna,3000,Analista,2014-02-18
8,Federica,Blu,federica.blu@example.com,29,Genova,3500,Team Leader,2013-12-12
9,Alessandro,Rosa,alessandro.rosa@example.info,31,Padova,4000,Project Manager,2009-08-01

In [17]:
# definisce il percorso del csv dove salvare il DataFrame
percorso_file = r'D:\Corso completo di Python\Intermedio\data\dipendenti.csv'

# Salvataggio del DataFrame in csv
df.to_csv(percorso_file, index=False)